DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 148, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 111, in build_exam
    pr_q2 = EasyPracticeCppQuestion.objects.all()[random.randint(0, easy_pracitce_count)]
NameError: name 'easy_pracitce_count' is not defined
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 148, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 91, in build_exam
    th_q5 = HardTheoryCppQuestion.objects.all()[random.randint(0, hard_theory_count)]
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
DEBUG:root:Total number of medium practice questions: 4
DEBUG:root:Total number of hard practice questions: 5
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
DEBUG:root:Total number of medium practice questions: 4
DEBUG:root:Total number of hard practice questions: 5
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
DEBUG:root:Total number of medium practice questions: 4
DEBUG:root:Total number of hard practice questions: 5
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
DEBUG:root:Total number of medium practice questions: 4
DEBUG:root:Total number of hard practice questions: 5
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 151, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 81, in build_exam
    assert easy_theory_count >= 10, "Not enough easy theory questions"
AssertionError: Not enough easy theory questions
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 155, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 92, in build_exam
    th_q3_offset, th_q4_offset = random.sample(range(easy_theory_count), 10)
  File "/usr/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 155, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 89, in build_exam
    assert easy_theory_count >= 20, logging.CRITICAL("Not enough easy theory questions")
TypeError: 'int' object is not callable
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Not enough easy theory questions
ERROR:django.request:Internal Server Error: /generate_exam
Traceback (most recent call last):
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bachdo/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 155, in generate_exam
    build_exam(buffer)
  File "/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py", line 89, in build_exam
    assert easy_theory_count >= 20, logging.debug("Not enough easy theory questions")
AssertionError: None
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
CRITICAL:root:AssertionError
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
DEBUG:root:Generating C++ exam pdf file response to user...
DEBUG:root:Total number of easy theory questions: 5
DEBUG:root:Total number of medium theory questions: 4
DEBUG:root:Total number of hard theory questions: 4
DEBUG:root:Total number of easy practice questions: 4
CRITICAL:root:Unexpected error: <class 'AssertionError'>
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
INFO:django.utils.autoreload:/media/bachdo/nibbana/nibbana/webDevelopment/LGE/cpp_exam_bank/cpp_exam_bank/exam_generation/views.py changed, reloading.
